### ISSUE TITLE
FEATURE REQUEST: Stagger settings

### ISSUE THREAD

**Issue by 919Studios** [fromtheoutfit/fadable#2]
# FEATURE REQUEST: Stagger settings
## The controls you have here are very useful to get fadable customized:
1. https://github.com/fromtheoutfit/fadable/blob/d31307ed3ed5e7a4c7ae9b016903f3c98c1f45fb/html/fadable.js#L5
2. https://github.com/fromtheoutfit/fadable/blob/d31307ed3ed5e7a4c7ae9b016903f3c98c1f45fb/html/fadable.js#L9
3. https://github.com/fromtheoutfit/fadable/blob/d31307ed3ed5e7a4c7ae9b016903f3c98c1f45fb/html/fadable.js#L12

### It would be cool if Fadable had:
// Configure: Stagger setting

**Comment by marcamos** [comment]
What do you mean by _stagger_?

**Comment by marcamos** [comment]
@919Studios Does this issue still stand?

**Comment by 919Studios** [comment]
was just a feature request/enhancement, no issues.
