### ISSUE TITLE
Browser "Print" command *hides* elements with ".fadable"

### ISSUE THREAD

**Issue by 919Studios** [fromtheoutfit/fadable#3]
# FADABLE BUG - Print styles
*See attached GIF for demonstration of this bug/issue.*

## POSSIBLE SOLUTIONS:
- Modify the **[Fadable JS file](https://raw.githubusercontent.com/fromtheoutfit/fadable/master/html/fadable.js)** to remove `.fadable` class during print operation.

- An addition to **[Fadable CSS file](https://raw.githubusercontent.com/fromtheoutfit/fadable/master/html/styles.css)** to render the `.fadable` class *useless* during print operation.

-----

![fadablePrintBugDemo](https://user-images.githubusercontent.com/20955174/76133456-3b495580-5fe6-11ea-85ce-4bea50cf32b6.gif)

**Comment by marcamos** [comment]
Great catch; I'll correct this soon.

**Comment by 919Studios** [comment]
# Please re-open this issue, still having bugs with fadable.

## NOTES:
When going to print, elements outside the viewport with class `.fadable` are *invisible* when user attempts to use browsers Print menu command.  Here is a visual example of the issue: 
![fadableIssueVisualExample](https://user-images.githubusercontent.com/20955174/76133456-3b495580-5fe6-11ea-85ce-4bea50cf32b6.gif)
